import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { fixturePath } from "../testing/fixtures.ts";
import { hasProvidedToYouTube, parseYouTubeDescription } from "./youtube-description.ts";

interface YtdlpEntry {
  readonly id: string;
  readonly title: string;
  readonly description: string;
}

const playlist = JSON.parse(
  readFileSync(fixturePath("ytdlp/playlist-discovery.json"), "utf8"),
) as YtdlpEntry[];
const video = JSON.parse(
  readFileSync(fixturePath("ytdlp/video-one-more-time.json"), "utf8"),
) as YtdlpEntry;

describe("parseYouTubeDescription", () => {
  it("reads the fixture's auto-generated description", () => {
    const parsed = parseYouTubeDescription(video.description);
    expect(parsed).not.toBeNull();
    expect(parsed?.label).toBe("Daft Life Ltd./ADA France");
    expect(parsed?.title).toBe("One More Time");
    expect(parsed?.artists).toEqual(["Daft Punk"]);
    expect(parsed?.album).toBe("Discovery");
    expect(parsed?.albumArtist).toBe("Daft Punk");
    expect(parsed?.releasedOn).toBe("2001-03-12");
    expect(parsed?.year).toBe(2001);
    expect(parsed?.copyright).toBe("℗ 2001 Daft Life Ltd., under exclusive license to ADA France");
  });

  it("reads every credit line with its role", () => {
    const parsed = parseYouTubeDescription(video.description);
    expect(parsed?.credits).toEqual([
      { role: "Producer", name: "Thomas Bangalter" },
      { role: "Producer", name: "Guy-Manuel de Homem-Christo" },
      { role: "Composer", name: "Thomas Bangalter" },
      { role: "Composer", name: "Guy-Manuel de Homem-Christo" },
    ]);
  });

  it("parses every entry of the playlist fixture", () => {
    const parsed = playlist.map((entry) => parseYouTubeDescription(entry.description));
    expect(parsed.every((entry) => entry !== null)).toBe(true);
    expect(parsed.map((entry) => entry?.album)).toEqual(Array<string>(15).fill("Discovery"));
    expect(parsed[14]?.title).toBe("One More Time (Radio Edit)");
  });

  it("falls back to the ℗ year when there is no 'Released on' line", () => {
    const parsed = parseYouTubeDescription(
      [
        "Provided to YouTube by Because Music",
        "",
        "Instant Crush · Daft Punk",
        "",
        "Random Access Memories",
        "",
        "℗ 2013 Daft Life Limited",
        "",
        "Auto-generated by YouTube.",
      ].join("\n"),
    );
    expect(parsed?.year).toBe(2013);
    expect(parsed?.releasedOn).toBeNull();
    expect(parsed?.title).toBe("Instant Crush");
  });

  it("reads a multi-artist title line", () => {
    const parsed = parseYouTubeDescription(
      [
        "Provided to YouTube by Columbia",
        "",
        "Get Lucky · Daft Punk · Pharrell Williams · Nile Rodgers",
        "",
        "Random Access Memories",
        "",
        "℗ 2013 Daft Life Limited",
        "",
        "Auto-generated by YouTube.",
      ].join("\n"),
    );
    expect(parsed?.title).toBe("Get Lucky");
    expect(parsed?.artists).toEqual(["Daft Punk", "Pharrell Williams", "Nile Rodgers"]);
    expect(parsed?.albumArtist).toBe("Daft Punk");
  });

  it("reads the album disambiguation in parentheses", () => {
    const parsed = parseYouTubeDescription(
      [
        "Provided to YouTube by Virgin",
        "",
        "Aerodynamic · Daft Punk",
        "",
        "Discovery (Remastered) [Deluxe]",
        "",
        "℗ 2001 Virgin",
        "",
        "Auto-generated by YouTube.",
      ].join("\n"),
    );
    expect(parsed?.album).toBe("Discovery");
    expect(parsed?.albumDisambiguation).toBe("Remastered");
  });

  it("uses the performers as artists when the title line has none", () => {
    const parsed = parseYouTubeDescription(
      [
        "Provided to YouTube by NAXOS",
        "",
        "Nocturne in E-flat major",
        "",
        "Chopin: Nocturnes",
        "",
        "Associated Performer: Idil Biret",
        "",
        "Auto-generated by YouTube.",
      ].join("\n"),
    );
    expect(parsed?.artists).toEqual(["Idil Biret"]);
    expect(parsed?.performers).toEqual(["Idil Biret"]);
  });

  it("returns null for anything that is not auto-generated", () => {
    expect(parseYouTubeDescription(null)).toBeNull();
    expect(parseYouTubeDescription("")).toBeNull();
    expect(parseYouTubeDescription("   ")).toBeNull();
    expect(parseYouTubeDescription("Check out my new album! Subscribe for more.")).toBeNull();
  });
});

/**
 * The one detection behind `officialUploadsOnly`.
 *
 * The owner's measurement on 9766 real sources is what makes this the right question to ask:
 * the line is present on 9544 and absent on 222, while the channel name — the obvious
 * alternative — is empty on 5306 of them and carries the `- Topic` suffix on only 580.
 */
describe("hasProvidedToYouTube", () => {
  it("finds the line in a real auto-generated description", () => {
    expect(hasProvidedToYouTube(video.description)).toBe(true);
    for (const entry of playlist) expect(hasProvidedToYouTube(entry.description)).toBe(true);
  });

  it("says no when the description is hand-written, empty or absent", () => {
    expect(hasProvidedToYouTube("Check out my new album! Subscribe for more.")).toBe(false);
    expect(hasProvidedToYouTube("")).toBe(false);
    expect(hasProvidedToYouTube("   ")).toBe(false);
    expect(hasProvidedToYouTube(null)).toBe(false);
    expect(hasProvidedToYouTube(undefined)).toBe(false);
  });

  it("does not care how YouTube capitalised it", () => {
    expect(hasProvidedToYouTube("provided to youtube by Parlophone")).toBe(true);
    expect(hasProvidedToYouTube("PROVIDED TO YOUTUBE BY Parlophone")).toBe(true);
    expect(hasProvidedToYouTube("Provided To YouTube By Parlophone")).toBe(true);
  });

  it("finds it wherever in the description it sits, including behind line breaks", () => {
    expect(hasProvidedToYouTube("\r\nProvided to YouTube by Virgin\r\n\r\nDiscovery")).toBe(true);
    expect(
      hasProvidedToYouTube(
        ["Music video by Daft Punk", "", "Provided to YouTube by Virgin", "℗ 2001"].join("\n"),
      ),
    ).toBe(true);
  });

  it("is not fooled by a line break inside the marker itself", () => {
    // Half the sentence on each of two lines is not the sentence. Better a false negative
    // here — one video refused — than a rule that matches on "Provided to".
    expect(hasProvidedToYouTube("Provided to\nYouTube by Virgin")).toBe(false);
  });

  it("is the same detection the parser uses to decide a description is auto-generated", () => {
    // A description carrying nothing but the line still parses; one carrying neither it nor
    // "Auto-generated by YouTube" does not. Two answers, one string.
    const marked = "Provided to YouTube by Virgin\n\nOne More Time\n\nDiscovery";
    expect(hasProvidedToYouTube(marked)).toBe(true);
    expect(parseYouTubeDescription(marked)).not.toBeNull();

    const unmarked = "One More Time\n\nDiscovery";
    expect(hasProvidedToYouTube(unmarked)).toBe(false);
    expect(parseYouTubeDescription(unmarked)).toBeNull();
  });
});
