/**
 * Parser for the description YouTube auto-generates on "Topic" channels.
 *
 * Ported from the v1 C# implementation, `v1/libs/MusicDownloader/YoutubeHelpers.cs`
 * (`ParseDescription` and its helpers). The regexes, the "first two significant lines"
 * heuristic and the artist-refinement rule are the same; what changed is that .NET's repeated
 * capture groups do not exist in JavaScript, so the `Title · Artist · Artist` line is split
 * rather than matched, and that credits are returned with their role instead of being sorted
 * into two buckets.
 *
 * What it yields feeds several tags of `docs/03-metadonnees.md` §2: `LABEL` and the
 * release-matching label signal, `COPYRIGHT` from the ℗ line, `DATE` from `Released on:`,
 * and `PRODUCER` / `COMPOSER` / `LYRICIST` / `PERFORMER` as a fallback when MusicBrainz has
 * no relation for the recording.
 *
 * Pure function; no I/O.
 */

/** One `Role: Name` line of the credits block. */
export interface YouTubeCredit {
  readonly role: string;
  readonly name: string;
}

export interface YouTubeDescription {
  readonly label: string | null;
  readonly title: string | null;
  readonly artists: readonly string[];
  readonly album: string | null;
  readonly albumDisambiguation: string | null;
  readonly albumArtist: string | null;
  /** From `Released on:` when present, else the ℗ year. */
  readonly year: number | null;
  /** `YYYY-MM-DD`, only when the description carries a `Released on:` line. */
  readonly releasedOn: string | null;
  /** The ℗ line verbatim, which is what `COPYRIGHT` is written from. */
  readonly copyright: string | null;
  readonly performers: readonly string[];
  readonly credits: readonly YouTubeCredit[];
}

const PROVIDED_BY = /Provided to YouTube by\s+(.*?)(?:\r?\n|$)/i;
const RELEASED_ON = /Released on:\s*(\d{4}-\d{2}-\d{2})/i;
const COPYRIGHT_LINE = /^\s*[℗©].*$/m;
const COPYRIGHT_YEAR = /[℗©]\s*(\d{4})\b/;
const ALBUM_LINE = /^\s*([^[(]+?)(?:\s*\((.*?)\))?(?:\s*\[.*?\])?\s*$/;

/**
 * The credit roles YouTube emits. Kept as an explicit list, exactly as the v1 parser had it:
 * an open-ended `Word:` pattern swallows half the description ("Music video by:", URLs…).
 */
const CREDIT_ROLES = [
  "Associated Performer",
  "Composer",
  "Lyricist",
  "Writer",
  "Producer",
  "Vocal Producer",
  "Engineer",
  "Mixing Engineer",
  "Recording Engineer",
  "Mastering Engineer",
  "Studio Personnel",
  "Arranger",
  "Conductor",
  "Coordinator",
] as const;

const CREDIT_LINE = new RegExp(`^\\s*(${CREDIT_ROLES.join("|")}):\\s*(.+?)\\s*$`, "i");

const KNOWN_PREFIXES = [
  "provided to youtube by",
  "auto-generated by youtube",
  "released on:",
  "℗",
  "©",
  ...CREDIT_ROLES.map((role) => `${role.toLowerCase()}:`),
];

function isKnownMetadataLine(line: string): boolean {
  const lowered = line.toLowerCase();
  return KNOWN_PREFIXES.some((prefix) => lowered.startsWith(prefix));
}

/**
 * Parse an auto-generated YouTube description.
 *
 * Returns `null` when the description is empty, when it carries neither
 * "Provided to YouTube by" nor "Auto-generated by YouTube" (a hand-written description tells
 * us nothing reliable), or when neither a title nor an album could be read — the same three
 * bail-outs as the v1 parser.
 */
export function parseYouTubeDescription(
  description: string | null | undefined,
): YouTubeDescription | null {
  if (description === null || description === undefined || description.trim() === "") return null;

  const lowered = description.toLowerCase();
  const autoGenerated =
    lowered.includes("provided to youtube by") || lowered.includes("auto-generated by youtube");
  if (!autoGenerated) return null;

  const label = PROVIDED_BY.exec(description)?.[1]?.trim() ?? null;
  const releasedOn = RELEASED_ON.exec(description)?.[1] ?? null;
  const copyright = COPYRIGHT_LINE.exec(description)?.[0]?.trim() ?? null;
  const copyrightYear = copyright === null ? null : (COPYRIGHT_YEAR.exec(copyright)?.[1] ?? null);

  const year =
    releasedOn !== null
      ? Number(releasedOn.slice(0, 4))
      : copyrightYear !== null
        ? Number(copyrightYear)
        : null;

  const lines = description
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line !== "");

  const credits: YouTubeCredit[] = [];
  for (const line of lines) {
    const match = CREDIT_LINE.exec(line);
    const role = match?.[1];
    const name = match?.[2];
    if (role !== undefined && name !== undefined) credits.push({ role, name });
  }
  const performers = credits
    .filter((credit) => credit.role.toLowerCase() === "associated performer")
    .map((credit) => credit.name);

  // Title, artists and album come from the first two lines that are not known metadata.
  const significant = lines.filter((line) => !isKnownMetadataLine(line)).slice(0, 2);
  const [firstLine, secondLine] = significant;

  let title: string | null = null;
  const artists: string[] = [];
  if (firstLine !== undefined) {
    // ".NET repeated captures" replacement: "Title · Artist · Artist" splits on the middle dot.
    const parts = firstLine.split("·").map((part) => part.trim());
    title = parts[0] ?? firstLine;
    for (const part of parts.slice(1)) if (part !== "") artists.push(part);
  }

  let album: string | null = null;
  let albumDisambiguation: string | null = null;
  if (secondLine !== undefined) {
    const match = ALBUM_LINE.exec(secondLine);
    album = match?.[1]?.trim() ?? secondLine;
    const disambiguation = match?.[2]?.trim();
    albumDisambiguation =
      disambiguation !== undefined && disambiguation !== "" ? disambiguation : null;
  }

  // v1's RefineArtists: fall back to the performers, then take the first artist as the album
  // artist. Both are heuristics of last resort — MusicBrainz overrides them at merge time.
  if (artists.length === 0) artists.push(...performers);
  const albumArtist = artists[0] ?? null;

  if (title === null && album === null) return null;

  return {
    label,
    title,
    artists,
    album,
    albumDisambiguation,
    albumArtist,
    year,
    releasedOn,
    copyright,
    performers,
    credits,
  };
}
