/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report liveness and which media tools this image actually carries.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Health
         * @description Payload of ``GET /health``. Mirrored in `packages/contracts`.
         */
        Health: {
            /** Fixtures */
            fixtures: boolean;
            /** Ok */
            ok: boolean;
            versions: components["schemas"]["ToolVersions"];
        };
        /**
         * ToolVersions
         * @description Version of each external tool, or ``None`` when it is missing from the image.
         */
        ToolVersions: {
            /** Ffmpeg */
            ffmpeg: string | null;
            /** Fpcalc */
            fpcalc: string | null;
            /** Rsgain */
            rsgain: string | null;
            /** Yt-Dlp */
            "yt-dlp": string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
