/**
 * Which toolbox contract this checkout was generated against.
 *
 * Generated by `bun run toolbox:openapi` — **never edit by hand**, like everything else
 * under `packages/contracts/toolbox/`.
 *
 * `GET /health` on the toolbox reports the same two values, computed from the document the
 * running image actually serves. When they differ, the container is not the one this code
 * was built for: every call that sends a field its models do not know about comes back as a
 * 422 `extra_forbidden`, which reads like a bug in the app and is not one. `get_status`
 * compares them and says so before anything fails.
 */
export const TOOLBOX_SCHEMA_VERSION = 1;

export const TOOLBOX_CONTRACT_HASH = "e0d497071ad88544";
