#!/usr/bin/env bun
/**
 * `bun run fixtures/v1/generate.ts` — write `dump.sql` from `dataset.ts`.
 *
 * The dump is committed, because a fixture you cannot read is not a fixture: `dump.sql` is
 * what somebody opens to see what a v1 database looks like, and it is loadable into any
 * Postgres with `psql -f`. It is *generated* so that it can never disagree with the file
 * builder, which reads the same description.
 *
 * The DDL reproduces v1's real schema: quoted PascalCase identifiers (EF Core with no naming
 * convention), enums as `character varying` holding the C# member name, and the three
 * `;`-joined list columns declared `NOT NULL` — because that is what v1's value converter
 * produces, and a reader that expected NULL there would be wrong.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { FIXTURE_FORCES, FIXTURE_PLAYLISTS, FIXTURE_SONGS, type FixtureSong } from "./dataset.ts";

const HERE = dirname(fileURLToPath(import.meta.url));

const DDL = `--
-- Reduced v1 database, for the P11 migration fixture.
--
-- Generated by \`bun run fixtures/v1/generate.ts\` from \`fixtures/v1/dataset.ts\`. Do not edit.
--
-- The schema is v1's own (\`v1/core/Data/Migrations/ApplicationDbContextModelSnapshot.cs\`):
-- EF Core with no naming convention, so every identifier is quoted PascalCase; every enum is
-- stored as its C# member name in a \`character varying\`; \`Genres\`, \`Performers\` and
-- \`AlbumArtists\` are \`;\`-joined strings and are NOT NULL (an empty list is '', never NULL).
--

DROP TABLE IF EXISTS "UserPlaylistSongs";
DROP TABLE IF EXISTS "UserPlaylists";
DROP TABLE IF EXISTS "SongForceMetadata";
DROP TABLE IF EXISTS "Songs";

CREATE TABLE "Songs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "SourceUrl" character varying(1024) NOT NULL,
    "SourceUrlParent" character varying(1024),
    "Platform" character varying(50) NOT NULL,
    "SourceId" varchar(100) NOT NULL,
    "SourceIdParent" varchar(100),
    "SourceTitle" text,
    "SourceDescription" text,
    "Title" character varying(500),
    "Subtitle" character varying(500),
    "Artist" character varying(500),
    "Performers" character varying(500) NOT NULL,
    "Album" character varying(500),
    "Isrc" text,
    "AlbumArtists" character varying(500) NOT NULL,
    "Year" integer,
    "TrackNumber" integer,
    "TrackCount" integer,
    "DiscNumber" integer,
    "DiscCount" integer,
    "Publisher" text,
    "Genres" text NOT NULL,
    "Duration" bigint,
    "DownloadStatus" character varying(50) NOT NULL,
    "FinalFilePath" character varying(2048),
    "LastAttempt" timestamp with time zone,
    "ErrorMessage" character varying(200000),
    "MusicBrainzRecordingId" uuid,
    "MusicBrainzReleaseId" uuid,
    "MusicBrainzReleaseGroupId" uuid,
    "MusicBrainzArtistId" uuid,
    "MusicBrainzAlbumArtistId" uuid,
    "MusicBrainzReleaseStatus" text,
    "MusicBrainzReleaseCountry" text,
    "MusicBrainzForced" boolean NOT NULL,
    "MusicBrainzRecordingIdForce" uuid,
    "MusicBrainzReleaseIdForce" uuid,
    "ForceSongMetadata" boolean NOT NULL,
    "ForceSourceMetadata" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Songs" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Songs_Platform_SourceId" ON "Songs" ("Platform", "SourceId");

CREATE TABLE "SongForceMetadata" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "SongId" integer NOT NULL,
    "Field" character varying(100) NOT NULL,
    "Value" text NOT NULL,
    "IsArrayValue" boolean NOT NULL,
    "GroupId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SongForceMetadata" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SongForceMetadata_Songs_SongId"
        FOREIGN KEY ("SongId") REFERENCES "Songs" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_SongForceMetadata_SongId_Field"
    ON "SongForceMetadata" ("SongId", "Field");

CREATE TABLE "UserPlaylists" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserPlaylists" PRIMARY KEY ("Id")
);

CREATE TABLE "UserPlaylistSongs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "PlaylistId" integer NOT NULL,
    "SongId" integer NOT NULL,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserPlaylistSongs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserPlaylistSongs_UserPlaylists_PlaylistId"
        FOREIGN KEY ("PlaylistId") REFERENCES "UserPlaylists" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserPlaylistSongs_Songs_SongId"
        FOREIGN KEY ("SongId") REFERENCES "Songs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UserPlaylistSongs_SongId" ON "UserPlaylistSongs" ("SongId");
CREATE UNIQUE INDEX "IX_UserPlaylistSongs_PlaylistId_SongId"
    ON "UserPlaylistSongs" ("PlaylistId", "SongId");
`;

/** A SQL literal. Single quotes doubled; nothing else is ever interpolated into the dump. */
function quote(value: string | number | boolean | null): string {
  if (value === null) return "NULL";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

/** v1's list converter, write side: `string.Join(';', v)`. Empty list is '', never NULL. */
function joinList(values: readonly string[]): string {
  return values.join(";");
}

const CREATED_AT = "2024-11-03T21:14:00Z";
const UPDATED_AT = "2025-04-18T09:32:00Z";

function songInsert(song: FixtureSong): string {
  const columns = [
    "Id",
    "SourceUrl",
    "SourceUrlParent",
    "Platform",
    "SourceId",
    "SourceIdParent",
    "SourceTitle",
    "SourceDescription",
    "Title",
    "Subtitle",
    "Artist",
    "Performers",
    "Album",
    "Isrc",
    "AlbumArtists",
    "Year",
    "TrackNumber",
    "TrackCount",
    "DiscNumber",
    "DiscCount",
    "Publisher",
    "Genres",
    "Duration",
    "DownloadStatus",
    "FinalFilePath",
    "LastAttempt",
    "ErrorMessage",
    "MusicBrainzRecordingId",
    "MusicBrainzReleaseId",
    "MusicBrainzReleaseGroupId",
    "MusicBrainzArtistId",
    "MusicBrainzAlbumArtistId",
    "MusicBrainzReleaseStatus",
    "MusicBrainzReleaseCountry",
    "MusicBrainzForced",
    "MusicBrainzRecordingIdForce",
    "MusicBrainzReleaseIdForce",
    "ForceSongMetadata",
    "ForceSourceMetadata",
    "CreatedAt",
    "UpdatedAt",
  ];

  const values = [
    quote(song.id),
    quote(song.sourceUrl),
    quote(song.sourceUrlParent),
    quote("YouTube"),
    quote(song.sourceId),
    quote(song.sourceIdParent),
    quote(song.sourceTitle),
    "NULL",
    quote(song.title),
    quote(song.subtitle),
    quote(song.artist),
    quote(joinList(song.performers)),
    quote(song.album),
    quote(song.isrc),
    quote(joinList(song.albumArtists)),
    quote(song.year),
    quote(song.trackNumber),
    quote(song.trackCount),
    quote(song.discNumber),
    quote(song.discCount),
    quote(song.publisher),
    quote(joinList(song.genres)),
    quote(song.duration),
    quote(song.downloadStatus),
    quote(song.finalFilePath),
    quote(UPDATED_AT),
    quote(song.errorMessage),
    quote(song.recordingMbid),
    quote(song.releaseMbid),
    quote(song.releaseGroupMbid),
    quote(song.artistMbid),
    quote(song.albumArtistMbid),
    quote(song.releaseStatus),
    quote(song.releaseCountry),
    quote(song.musicBrainzForced),
    quote(song.recordingMbidForce),
    quote(song.releaseMbidForce),
    quote(song.forceSongMetadata),
    quote(song.forceSourceMetadata),
    quote(CREATED_AT),
    quote(UPDATED_AT),
  ];

  return (
    `INSERT INTO "Songs" (${columns.map((name) => `"${name}"`).join(", ")})\n` +
    `VALUES (${values.join(", ")});`
  );
}

function build(): string {
  const parts: string[] = [DDL];

  parts.push("\n--\n-- Songs\n--\n");
  for (const song of FIXTURE_SONGS) parts.push(songInsert(song));

  parts.push("\n--\n-- SongForceMetadata\n--\n");
  for (const force of FIXTURE_FORCES) {
    parts.push(
      `INSERT INTO "SongForceMetadata" ("Id", "SongId", "Field", "Value", "IsArrayValue", "GroupId", "CreatedAt", "UpdatedAt")\n` +
        `VALUES (${quote(force.id)}, ${quote(force.songId)}, ${quote(force.field)}, ${quote(force.value)}, ` +
        `${quote(force.isArrayValue)}, NULL, ${quote(CREATED_AT)}, ${quote(UPDATED_AT)});`,
    );
  }

  parts.push("\n--\n-- UserPlaylists\n--\n");
  let linkId = 0;
  for (const playlist of FIXTURE_PLAYLISTS) {
    parts.push(
      `INSERT INTO "UserPlaylists" ("Id", "Name", "Description", "CreatedAt", "UpdatedAt")\n` +
        `VALUES (${quote(playlist.id)}, ${quote(playlist.name)}, ${quote(playlist.description)}, ` +
        `${quote(CREATED_AT)}, ${quote(UPDATED_AT)});`,
    );
  }

  parts.push("\n--\n-- UserPlaylistSongs\n--\n");
  for (const playlist of FIXTURE_PLAYLISTS) {
    playlist.songIds.forEach((songId, index) => {
      linkId += 1;
      parts.push(
        `INSERT INTO "UserPlaylistSongs" ("Id", "PlaylistId", "SongId", "Order", "CreatedAt", "UpdatedAt")\n` +
          `VALUES (${quote(linkId)}, ${quote(playlist.id)}, ${quote(songId)}, ${quote(index + 1)}, ` +
          `${quote(CREATED_AT)}, ${quote(UPDATED_AT)});`,
      );
    });
  }

  // The identity sequences must not collide with the explicit ids above.
  parts.push(
    "\n--\n-- keep the identity sequences ahead of the explicit ids\n--\n" +
      `SELECT setval(pg_get_serial_sequence('"Songs"', 'Id'), 1000, true);\n` +
      `SELECT setval(pg_get_serial_sequence('"SongForceMetadata"', 'Id'), 1000, true);\n` +
      `SELECT setval(pg_get_serial_sequence('"UserPlaylists"', 'Id'), 1000, true);\n` +
      `SELECT setval(pg_get_serial_sequence('"UserPlaylistSongs"', 'Id'), 1000, true);`,
  );

  return `${parts.join("\n")}\n`;
}

const target = join(HERE, "dump.sql");
writeFileSync(target, build(), "utf8");
console.log(
  `wrote ${target}: ${String(FIXTURE_SONGS.length)} songs, ${String(FIXTURE_FORCES.length)} force rows, ${String(FIXTURE_PLAYLISTS.length)} playlists`,
);
