// @vitest-environment node
import { describe, expect, it } from "vitest";
import { admit, attachedAlbum, isOfficialUpload, refusalOf } from "./source-rules.ts";
import type { SourceRules } from "./source-rules.ts";

/**
 * The two admission rules, asked of one video.
 *
 * The detection itself is `packages/domain`'s and is tested there against the recorded
 * descriptions; what is pinned here is the *policy* — which rule fires, what sentence it
 * leaves behind, and the definition of "no album attached", which has to keep agreeing with
 * the two fields `resolve` already reads.
 */

const OFF: SourceRules = { officialUploadsOnly: false, requireAlbum: false };
const OFFICIAL_ONLY: SourceRules = { officialUploadsOnly: true, requireAlbum: false };
const ALBUM_ONLY: SourceRules = { officialUploadsOnly: false, requireAlbum: true };

const PROVIDED = [
  "Provided to YouTube by Virgin",
  "",
  "One More Time · Daft Punk",
  "",
  "Discovery",
  "",
  "℗ 2001 Daft Life Ltd.",
  "",
  "Auto-generated by YouTube.",
].join("\n");

describe("isOfficialUpload", () => {
  it("reads the description, and only the description", () => {
    expect(isOfficialUpload({ description: PROVIDED })).toBe(true);
    expect(isOfficialUpload({ description: "PROVIDED TO YOUTUBE BY Virgin" })).toBe(true);
    expect(isOfficialUpload({ description: "my cover of One More Time" })).toBe(false);
    expect(isOfficialUpload({ description: null })).toBe(false);
    expect(isOfficialUpload({})).toBe(false);
  });
});

/**
 * The definition written into the `requireAlbum` doc string, asserted.
 *
 * Two sources, in `resolve`'s own order of trust: the YouTube Music `album` tag — the field
 * `classify()` counts to tell an album from a playlist — and then the album line of the
 * auto-generated description. Blank is not an album, because YouTube does emit blank tags.
 */
describe("attachedAlbum", () => {
  it("takes the YouTube Music album tag first", () => {
    expect(attachedAlbum({ album: "Discovery", description: PROVIDED })).toBe("Discovery");
    expect(attachedAlbum({ album: "Homework" })).toBe("Homework");
  });

  it("falls back to the album line of the auto-generated description", () => {
    expect(attachedAlbum({ album: null, description: PROVIDED })).toBe("Discovery");
  });

  it("calls a blank tag no album at all", () => {
    expect(attachedAlbum({ album: "   " })).toBeNull();
    expect(attachedAlbum({ album: "" })).toBeNull();
  });

  it("is null when neither source says anything", () => {
    expect(attachedAlbum({})).toBeNull();
    expect(attachedAlbum({ album: null, description: "Subscribe for more!" })).toBeNull();
  });
});

describe("admit — officialUploadsOnly", () => {
  it("lets everything through while the rule is off", () => {
    expect(admit({ description: null }, OFF, { isolated: true }).accept).toBe(true);
  });

  it("refuses a video with no “Provided to YouTube by” line, and says so", () => {
    const verdict = admit({ description: "a live set I filmed" }, OFFICIAL_ONLY, {
      isolated: true,
    });
    expect(verdict.accept).toBe(false);
    expect(verdict.code).toBe("SOURCE_NOT_OFFICIAL");
    expect(verdict.reason).toMatch(/Provided to YouTube by/);
  });

  it("accepts a distributor's upload whatever its casing", () => {
    expect(admit({ description: PROVIDED }, OFFICIAL_ONLY, { isolated: true }).accept).toBe(true);
    expect(
      admit({ description: "provided to youtube by X" }, OFFICIAL_ONLY, { isolated: false }).accept,
    ).toBe(true);
  });

  it("applies inside a playlist too — it is a fact about the video, not about the URL", () => {
    expect(admit({ description: null }, OFFICIAL_ONLY, { isolated: false }).accept).toBe(false);
  });
});

describe("admit — requireAlbum", () => {
  it("lets everything through while the rule is off", () => {
    expect(admit({ album: null }, OFF, { isolated: true }).accept).toBe(true);
  });

  it("refuses an isolated video with neither an album tag nor an album line", () => {
    const verdict = admit({ album: null, description: null }, ALBUM_ONLY, { isolated: true });
    expect(verdict.accept).toBe(false);
    expect(verdict.code).toBe("SOURCE_NO_ALBUM");
    expect(verdict.reason).toMatch(/No album attached/);
  });

  it("accepts it on the album tag alone", () => {
    expect(admit({ album: "Discovery" }, ALBUM_ONLY, { isolated: true }).accept).toBe(true);
  });

  it("accepts it on the description's album line alone", () => {
    expect(admit({ album: null, description: PROVIDED }, ALBUM_ONLY, { isolated: true })).toEqual({
      accept: true,
      reason: "",
      code: null,
    });
  });

  it("never fires inside a playlist: the playlist is the album", () => {
    expect(admit({ album: null, description: null }, ALBUM_ONLY, { isolated: false }).accept).toBe(
      true,
    );
  });

  it("is checked after the official rule, so the first refusal is the one reported", () => {
    const both: SourceRules = { officialUploadsOnly: true, requireAlbum: true };
    const verdict = admit({ album: null, description: null }, both, { isolated: true });
    expect(verdict.code).toBe("SOURCE_NOT_OFFICIAL");
  });
});

describe("refusalOf", () => {
  it("names the rule, the URL and the way out", () => {
    const verdict = admit({ description: null }, OFFICIAL_ONLY, { isolated: true });
    const error = refusalOf(verdict, "https://youtu.be/abc");
    expect(error.code).toBe("SOURCE_NOT_OFFICIAL");
    expect(error.message).toContain("https://youtu.be/abc");
    expect(error.hint).toMatch(/Official uploads only/);
    expect(error.details).toEqual({ url: "https://youtu.be/abc", rule: "officialUploadsOnly" });
    expect(error.status).toBe(422);
  });

  it("says something different for the album rule", () => {
    const verdict = admit({ album: null }, ALBUM_ONLY, { isolated: true });
    const error = refusalOf(verdict, "https://youtu.be/xyz");
    expect(error.code).toBe("SOURCE_NO_ALBUM");
    expect(error.message).toMatch(/no album attached/);
    expect(error.hint).toMatch(/Require an album/);
    expect(error.details).toEqual({ url: "https://youtu.be/xyz", rule: "requireAlbum" });
  });
});
