/**
 * Record the five matching scenarios from the real MusicBrainz.
 *
 * `bun run scripts/record-matching-cassettes.ts [name…] [--dry]`
 *
 * Run **once**, by hand, with `MM_MB_CONTACT` set. It writes two things per scenario:
 *
 *  - `apps/web/test/cassettes/matching/<name>.json` — every MusicBrainz document one match
 *    touches, under the exact cache key `integrations/musicbrainz.ts` computes for it. Seeding
 *    those rows and running the service `offline` replays the match without a socket.
 *  - `packages/domain/fixtures/matching/<name>.json` — the same documents reduced to the pure
 *    engine's input, so `packages/domain` can test the scoring without importing anything from
 *    `apps/web`.
 *
 * It obeys the one-request-per-second rule itself rather than borrowing the app's limiter,
 * because it must run without a database and the limiter lives behind the cache. The contact
 * is read from the environment and never printed: the User-Agent is the one thing MusicBrainz
 * asks for and the one thing that must not end up in a committed file.
 *
 * The requests it makes are exactly the ones the service makes, in the same order, decided by
 * the same pure engine — one release-group search, one release search per group kept, and the
 * top-N lookups chosen by pre-scoring the results here too (decision 151). A cassette is
 * therefore a recording of the real algorithm's appetite, not a guess at it.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  albumHints,
  DEFAULT_GROUP_LIMIT,
  DEFAULT_LOOKUP_LIMIT,
  lucene,
  releaseCandidates,
  releaseGroups,
  titleScore,
  type MatchVideo,
} from "../packages/domain/src/matching/index.ts";
import {
  creditCarriesArtist,
  primaryArtist,
  stripArtistPrefix,
  stripEditionQualifier,
} from "../packages/domain/src/normalize/title.ts";
import type {
  MbRecording,
  MbRelease,
  MbReleaseGroup,
} from "../packages/domain/src/metadata/resolvers/musicbrainz-types.ts";
import { prune } from "./prune-musicbrainz.ts";
import { repoRoot } from "./lib.ts";

/* ------------------------------------------------------------------ */
/* the scenarios                                                       */
/* ------------------------------------------------------------------ */

interface AlbumScenario {
  readonly name: string;
  readonly kind: "album";
  readonly source: {
    url: string;
    album: string;
    artist: string;
    year: number;
    label: string;
    note?: string;
  };
  readonly videos: readonly MatchVideo[];
}

interface SingleScenario {
  readonly name: string;
  readonly kind: "single";
  readonly source: { url: string; note?: string };
  readonly video: MatchVideo;
  /**
   * Other videos the same cassette must be able to answer.
   *
   * `videos[0]` is the scenario the phase table describes and the only one the pure-engine
   * fixture is built from — deliberately *not* what the toolbox fixture serves, which is the
   * whole point of a cassette that needs neither Docker nor a network. But the Console's
   * wizard resolves through the toolbox, so on `fixture://skinny-love` it matches the *other*
   * video, with a different artist clause and a different duration window, and the cassette
   * had no document for it: step 2 of a single could not be exercised offline at all
   * (DRIVE-1 §A1, when a spec was finally written for it). Recording both keeps the scenario
   * and makes the fixture pair usable end to end.
   */
  readonly alsoVideos?: readonly MatchVideo[];
}

type Scenario = AlbumScenario | SingleScenario;

interface AlbumCommon {
  readonly album: string;
  readonly artist: string;
  readonly year: number;
  readonly uploader: string;
  readonly label: string;
  readonly releasedOn: string;
}

/**
 * The "Auto-generated by YouTube" blurb, in the exact shape `normalize/youtube-description.ts`
 * parses. It is the only place the label and the exact release date ever appear, which is why
 * the matcher reads it at all.
 */
function autoDescription(of: AlbumCommon & { track: string }): string {
  return [
    `Provided to YouTube by ${of.label}`,
    "",
    `${of.track} · ${of.artist}`,
    "",
    of.album,
    "",
    `℗ ${String(of.year)} ${of.label}`,
    "",
    `Released on: ${of.releasedOn}`,
    "",
    "Auto-generated by YouTube.",
  ].join("\n");
}

/** Build an album's video list from `[title, seconds]` pairs, all sharing the YouTube tags. */
function albumVideos(
  entries: readonly (readonly [string, number, string?])[],
  common: AlbumCommon,
): MatchVideo[] {
  return entries.map(([title, duration, trackTag], index) => ({
    id: `yt-${common.album.toLowerCase().replace(/\W+/g, "-")}-${String(index + 1)}`,
    index,
    title,
    durationSeconds: duration,
    uploader: common.uploader,
    ytTrack: trackTag ?? title,
    ytArtist: common.artist,
    ytAlbum: common.album,
    ytReleaseYear: common.year,
    description: autoDescription({ ...common, track: trackTag ?? title }),
  }));
}

const DISCOVERY: AlbumScenario = {
  name: "discovery",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_discovery",
    album: "Discovery",
    artist: "Daft Punk",
    year: 2001,
    // "Provided to YouTube by Parlophone France" — the distributor today, not the 2001 imprint.
    label: "Parlophone France",
    note: "15 videos for a 14-track album: the last one is a radio edit and must end up extra.",
  },
  videos: albumVideos(
    [
      ["One More Time", 320],
      ["Aerodynamic", 207],
      ["Digital Love", 298],
      ["Harder Better Faster Stronger", 224, "Harder, Better, Faster, Stronger"],
      ["Crescendolls", 211],
      ["Nightvision", 104],
      ["Superheroes", 238],
      ["High Life", 202],
      ["Something About Us", 231],
      ["Voyager", 227],
      ["Veridis Quo", 344],
      ["Short Circuit", 206],
      ["Face to Face", 238],
      ["Too Long", 600],
      ["One More Time (Radio Edit)", 233, "One More Time"],
    ],
    {
      album: "Discovery",
      artist: "Daft Punk",
      year: 2001,
      uploader: "Daft Punk - Topic",
      label: "Parlophone (France)",
      releasedOn: "2001-03-12",
    },
  ),
};

const CURRENTS: AlbumScenario = {
  name: "currents",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_currents",
    album: "Currents",
    artist: "Tame Impala",
    year: 2015,
    label: "Modular Recordings",
    note: "11 videos for a 13-track album: “Gossip” and “Disciples” are missing and must be reported uncovered.",
  },
  // Durations within a second of the release's own, which is what a YouTube Music rip looks
  // like, and titles in YouTube's title case with straight apostrophes — so the normaliser is
  // exercised rather than bypassed. Tracks 6 (Gossip) and 9 (Disciples) have no video.
  videos: albumVideos(
    [
      ["Let It Happen", 467],
      ["Nangs", 108],
      ["The Moment", 254],
      ["Yes I'm Changing", 270],
      ["Eventually", 320],
      ["The Less I Know The Better", 218],
      ["Past Life", 226],
      ["'Cause I'm A Man", 241],
      ["Reality In Motion", 252],
      ["Love/Paranoia", 187],
      ["New Person, Same Old Mistakes", 363],
    ],
    {
      album: "Currents",
      artist: "Tame Impala",
      year: 2015,
      uploader: "Tame Impala - Topic",
      label: "Modular Recordings",
      releasedOn: "2015-07-17",
    },
  ),
};

const SKINNY_LOVE: SingleScenario = {
  name: "skinny-love",
  kind: "single",
  source: {
    url: "https://www.youtube.com/watch?v=skinny-love",
    note: "Birdy's cover, not Bon Iver's original: same title, same song, thirty-six seconds apart.",
  },
  video: {
    id: "yt-skinny-love",
    index: 0,
    title: "Birdy - Skinny Love [Official Music Video]",
    durationSeconds: 202,
    uploader: "Birdy",
    ytTrack: "Skinny Love",
    ytArtist: "Birdy",
    ytAlbum: "Birdy",
    ytReleaseYear: 2011,
  },
  // Verbatim from `services/toolbox/src/toolbox/fixtures/data/skinny-love.json`, so that
  // `fixture://skinny-love` replays in the Console exactly as it does in `mm match`.
  alsoVideos: [
    {
      id: "MVzhTGx2Lec",
      index: 0,
      title: "Skinny Love",
      durationSeconds: 238,
      uploader: "Bon Iver - Topic",
      ytTrack: "Skinny Love",
      ytArtist: "Bon Iver",
      ytAlbum: "For Emma, Forever Ago",
      ytReleaseYear: 2007,
    },
  ],
};

const FORMIDABLE: SingleScenario = {
  name: "formidable",
  kind: "single",
  source: {
    url: "https://www.youtube.com/watch?v=formidable",
    note: "Album version 3:34 against the single edit 3:33 — one second apart, which is inside the tolerance.",
  },
  video: {
    id: "yt-formidable",
    index: 0,
    title: "Stromae - Formidable (clip officiel)",
    durationSeconds: 214,
    uploader: "Stromae",
    ytTrack: "Formidable",
    ytArtist: "Stromae",
    ytReleaseYear: 2013,
  },
};

/**
 * The third owner review's counter-example, recorded from the real thing.
 *
 * Eleven videos of Tessa Violet's *Bad Ideas*, exactly as `yt-dlp` reports the YouTube Music
 * album playlist `OLAK5uy_lMECD_…`. MusicBrainz files that name four ways — the 2019 album,
 * a 2022 deluxe vinyl in the same group, a 2019 EP called "Bad Ideas (Act One)", and a 2020
 * one-track single — which is what made the single-group search of the previous algorithm
 * offer one candidate at 94 %. It is here so that never becomes true again silently.
 */
const BAD_IDEAS: AlbumScenario = {
  name: "bad-ideas",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_lMECD_tHQnZ8tr8_mQZr2I8usqrw9eCrs",
    album: "Bad Ideas",
    artist: "Tessa Violet",
    year: 2019,
    label: "T∆G Music",
    note: "11 videos, and four release groups share the name: album, deluxe, EP, and a one-track single. The single must not win (owner review 3, D3).",
  },
  videos: albumVideos(
    [
      ["Prelude", 64],
      ["Crush", 216],
      ["Bad Ideas", 179],
      ["I Like (the idea of) You", 170],
      ["Games", 221],
      ["Feelin", 184],
      ["Words Ain't Enough", 124],
      ["Bored", 183],
      ["Wishful Drinking", 195],
      ["Honest", 252],
      ["Interlude III", 170],
    ],
    {
      album: "Bad Ideas",
      artist: "Tessa Violet",
      year: 2019,
      uploader: "Tessa Violet",
      label: "T∆G Music",
      releasedOn: "2019-10-25",
    },
  ),
};

/**
 * The fifth owner review's counter-example: two pressings, one of them with no picture.
 *
 * Ten videos of the YouTube Music album playlist `OLAK5uy_k3ckSBQqo8bkgLY4h8dkRc4ky0NFdY3To`.
 * MusicBrainz has *Pure Heroine* as one release group with a great many pressings, two of
 * which matter here and are in the recording: the 2013 US Lava release
 * `f546b766-4b04-4781-b058-3d5e7dabc37d`, whose `cover-art-archive` says
 * `{artwork: false, front: false, count: 0}`, and the 2014 worldwide Universal release
 * `002022bb-276c-455a-8cb9-2848b77c37b8`, which has a front. Before decision 167 the first
 * one was preselected at 99 % against the second's 98 % — the same ten tracks, and no cover.
 */
const PURE_HEROINE: AlbumScenario = {
  name: "pure-heroine",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_k3ckSBQqo8bkgLY4h8dkRc4ky0NFdY3To",
    album: "Pure Heroine",
    artist: "Lorde",
    year: 2013,
    label: "Universal Music Group",
    note: "10 videos, one release group, many pressings: the US 2013 one has no cover art and the XW 2014 one does (owner review 5, G1).",
  },
  videos: albumVideos(
    [
      ["Tennis Court", 199],
      ["400 Lux", 234],
      ["Royals", 190],
      ["Ribs", 259],
      ["Buzzcut Season", 247],
      ["Team", 193],
      ["Glory And Gore", 211],
      ["Still Sane", 188],
      ["White Teeth Teens", 217],
      ["A World Alone", 294],
    ],
    {
      album: "Pure Heroine",
      artist: "Lorde",
      year: 2013,
      uploader: "Lorde - Topic",
      label: "Universal Music Group",
      releasedOn: "2013-01-01",
    },
  ),
};

/**
 * The sixth owner review's counter-example: an edition that fits *exactly*, ranked twelfth.
 *
 * Fourteen videos of the YouTube Music album playlist for *Appeal to Reason*. MusicBrainz has
 * the release group fourteen times over, and two of those pressings are the whole case:
 *
 *  - `b5ae03f1-0980-4c67-ae20-e9635b69f404` — XW, 2008-10, Digital Media, **fifteen** tracks,
 *    the fifteenth being "Prayer of the Refugee (live)". It places all fourteen videos and
 *    leaves that live bonus track claimed by nobody. It is the one the engine used to choose.
 *  - `46a691d9-67f7-42c1-bc91-7689b0a7fade` — XW, 2014-09-12, Digital Media, Geffen,
 *    **fourteen** tracks ending on "Elective Amnesia (single version)". It fits the playlist
 *    exactly, in order, with no orphan on either side — and it is the digital master YouTube
 *    actually serves. On metadata alone it ranked **twelfth**, so the six-lookup plan never
 *    read its tracklist and it sat at "0 videos matched".
 *
 * Both halves of this repository's answer are recorded here: the adaptive exploration has to
 * reach the twelfth candidate, and `exactness` has to prefer it once it is read.
 *
 * The video durations are the 2014 master's, because that is the one YouTube Music streams;
 * the 2008 edition is within the ±2 s tolerance on all fourteen, which is exactly why the fit
 * alone could never separate the two.
 */
const RISE_AGAINST: AlbumScenario = {
  name: "rise-against",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_appeal-to-reason",
    album: "Appeal to Reason",
    artist: "Rise Against",
    year: 2008,
    label: "Geffen Records",
    note: "14 videos. A 15-track edition places all of them and leaves a live bonus track over; a 14-track edition fits exactly and ranked twelfth (owner review 6).",
  },
  videos: albumVideos(
    [
      ["Collapse (Post-Amerika)", 199],
      ["Long Forgotten Sons", 242],
      ["Re-Education (Through Labor)", 222],
      ["The Dirt Whispered", 189],
      ["Kotov Syndrome", 185],
      ["From Heads Unworthy", 222],
      ["The Strength to Go On", 207],
      ["Audience of One", 245],
      ["Entertainment", 215],
      ["Hero of War", 253],
      ["Savior", 242],
      ["Hairline Fracture", 243],
      ["Whereabouts Unknown", 242],
      ["Elective Amnesia", 236],
    ],
    {
      album: "Appeal to Reason",
      artist: "Rise Against",
      year: 2008,
      uploader: "Rise Against - Topic",
      label: "Geffen Records",
      releasedOn: "2008-10-07",
    },
  ),
};

/**
 * The sixth owner review's worst case: somebody else's album, imported under a plausible name.
 *
 * Fourteen videos of Laufey's *Bewitched*, credited by YouTube to "**Laufey, Spencer
 * Stewart**" — the artist and her producer, in one string, which is what YouTube Music does
 * and what MusicBrainz has never heard of. `releasegroup:"Bewitched" AND artist:"Laufey,
 * Spencer Stewart"` really does answer `count: 0`; the version this scenario exists to bury
 * then asked `release:"Bewitched"` alone, got a hundred and forty-two records by everybody who
 * ever used the word, and imported **Laura Fygi's** 1993 album — twelve tracks, seven of the
 * fourteen videos placed, score 0.537 — while its own card said "Artist mismatch".
 *
 * Two rules have to hold on this recording, and between them they are the fix:
 *
 *  - the first rung of the ladder asks for the **first credited artist**, "Laufey", which
 *    MusicBrainz answers with three release groups, one of them the album;
 *  - nothing credited to anyone else can win, and if the whole list ever were somebody else's,
 *    the artist gate refuses instead of preselecting.
 */
const BEWITCHED: AlbumScenario = {
  name: "bewitched",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_bewitched",
    album: "Bewitched",
    artist: "Laufey, Spencer Stewart",
    year: 2023,
    label: "AWAL Recordings America",
    note: "14 videos credited to the artist AND her producer. The composite credit finds nothing; the engine used to drop the artist and import Laura Fygi's 1993 album (owner review 6, D1/D2).",
  },
  videos: albumVideos(
    [
      ["Dreamer", 210],
      ["Second Best", 204],
      ["Haunted", 200],
      ["Must Be Love", 184],
      ["While You Were Sleeping", 177],
      ["Lovesick", 225],
      ["California and Me", 216],
      ["Nocturne (interlude)", 144],
      ["Promise", 234],
      ["From the Start", 169],
      ["Misty", 209],
      ["Serendipity", 219],
      ["Letter to My 13 Year Old Self", 262],
      ["Bewitched", 246],
    ],
    {
      album: "Bewitched",
      artist: "Laufey, Spencer Stewart",
      year: 2023,
      uploader: "Laufey - Topic",
      label: "AWAL Recordings America",
      releasedOn: "2023-09-08",
    },
  ),
};

/**
 * Three of the sixth review's defects in one playlist, which is why it is worth its requests.
 *
 * The owner's source is a YouTube Music album titled, verbatim, **"The Heist (Deluxe
 * Edition)"** by **Macklemore & Ryan Lewis**, eighteen videos. Every rung of the ladder and
 * both halves of the penalty rule are exercised by that one string:
 *
 *  - `artist:"Macklemore & Ryan Lewis"` answers nothing — MusicBrainz files the record under
 *    exactly that credit and its search index still will not answer the phrase — while
 *    `artist:"Macklemore"`, the first credited name, answers with one release group. The
 *    owner's library holds this album attributed to **Crockett**, which is what the artist-less
 *    retry proposed;
 *  - `releasegroup:"The Heist (Deluxe Edition)"` answers nothing either, because MusicBrainz
 *    names the *record* and puts the edition in a disambiguation. So the base-title rung is the
 *    one that finds it, and this is the scenario that proves it against the real index;
 *  - and then the deluxe pressing — eighteen tracks, eighteen videos, mean Δ 0.3 s, a perfect
 *    match — used to be marked down twenty points for the word "deluxe" in its comment, to
 *    76 %, because the penalty was absolute. The source *announced* deluxe. It is the only
 *    right answer and it was the only one being punished.
 *
 * Recorded next to *Bewitched* because "&" and "," are different code paths in
 * `splitArtistCredit` and only one of them would have been exercised otherwise.
 */
const THE_HEIST: AlbumScenario = {
  name: "the-heist",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_the-heist-deluxe",
    album: "The Heist (Deluxe Edition)",
    artist: "Macklemore & Ryan Lewis",
    year: 2012,
    label: "Macklemore LLC",
    note: "18 videos, a duo credit MusicBrainz will not answer as a phrase, and a title carrying the edition. The deluxe pressing is the right answer and used to be the only one penalised (owner review 6, D1/D2/D5).",
  },
  videos: albumVideos(
    [
      ["Ten Thousand Hours", 250],
      ["Can't Hold Us", 258],
      ["Thrift Shop", 237],
      ["Thin Line", 256],
      ["Same Love", 320],
      ["Make the Money", 225],
      ["Neon Cathedral", 274],
      ["BomBom", 296],
      ["White Walls", 220],
      ["Jimmy Iovine", 233],
      ["Wing$", 300],
      ["A Wake", 226],
      ["Gold", 252],
      ["Starting Over", 251],
      ["Cowboy Boots", 258],
      ["Castle", 258],
      ["My Oh My", 257],
      ["Victory Lap", 214],
    ],
    {
      album: "The Heist (Deluxe Edition)",
      artist: "Macklemore & Ryan Lewis",
      year: 2012,
      uploader: "Macklemore & Ryan Lewis - Topic",
      label: "Macklemore LLC",
      releasedOn: "2012-10-09",
    },
  ),
};

const SCENARIOS: readonly Scenario[] = [
  DISCOVERY,
  SKINNY_LOVE,
  CURRENTS,
  FORMIDABLE,
  BAD_IDEAS,
  PURE_HEROINE,
  RISE_AGAINST,
  BEWITCHED,
  THE_HEIST,
];

/* ------------------------------------------------------------------ */
/* the wire                                                            */
/* ------------------------------------------------------------------ */

const BASE = "https://musicbrainz.org/ws/2";
const MIN_INTERVAL_MS = 1_100; // a little over one second, so a clock skew cannot make it two

/** `inc=` lists — kept in step with `apps/web/src/server/integrations/musicbrainz.ts`. */
const INC = {
  releaseFull:
    "artists+artist-credits+labels+recordings+release-groups+media+isrcs+genres+tags+aliases+artist-rels+recording-rels+work-rels+recording-level-rels+work-level-rels+url-rels",
  // The matcher looks a recording up to learn which releases it is on, so it asks for the
  // app.s `recordingBorrow` preset — the same list, under the same cache key.
  recordingBorrow:
    "artists+artist-credits+isrcs+genres+tags+aliases+artist-rels+work-rels+url-rels+work-level-rels+releases+release-groups+media",
} as const;

let lastCall = 0;
let requests = 0;

function readContact(): string {
  const fromEnv = process.env["MM_MB_CONTACT"];
  if (fromEnv !== undefined && fromEnv.trim() !== "") return fromEnv.trim();
  const envFile = join(repoRoot, ".env");
  if (existsSync(envFile)) {
    for (const line of readFileSync(envFile, "utf8").split(/\r?\n/)) {
      const match = /^\s*MM_MB_CONTACT\s*=\s*(.*)$/.exec(line);
      if (match?.[1] !== undefined) return match[1].trim().replace(/^["']|["']$/g, "");
    }
  }
  throw new Error(
    "MM_MB_CONTACT is not set. Put it in v2/.env (gitignored) before recording cassettes.",
  );
}

const USER_AGENT = `MusicManager/0.0.0 ( ${readContact()} )`;

async function pace(): Promise<void> {
  const wait = lastCall + MIN_INTERVAL_MS - Date.now();
  if (wait > 0) await new Promise((r) => setTimeout(r, wait));
  lastCall = Date.now();
}

/**
 * One request, paced and retried.
 *
 * `503` from MusicBrainz means "busy", not "wrong": the `inc=` list of a full release lookup
 * is expensive and their load-shedder says so several times an hour. Backing off and asking
 * again is the documented answer, and a recorder that gave up on the first one would have to
 * be babysat through a four-scenario run.
 */
async function get<T>(path: string, query: Record<string, string>): Promise<T> {
  const search = new URLSearchParams({ ...query, fmt: "json" });
  const url = `${BASE}/${path}?${search.toString()}`;
  let backoff = 2_000;

  for (let attempt = 1; ; attempt += 1) {
    await pace();
    const response = await fetch(url, { headers: { "user-agent": USER_AGENT } });
    requests += 1;
    if (response.ok) return prune(await response.json()) as T;

    const body = await response.text();
    const retryable = response.status === 503 || response.status === 429 || response.status >= 500;
    if (!retryable || attempt >= MAX_ATTEMPTS) {
      throw new Error(`MusicBrainz answered ${String(response.status)} for ${path} — ${body}`);
    }
    console.log(`  ${String(response.status)} on ${path}, retrying in ${String(backoff / 1000)}s…`);
    await new Promise((r) => setTimeout(r, backoff));
    backoff = Math.min(backoff * 2, 60_000);
  }
}

/**
 * How many times one document is asked for before the run gives up on it.
 *
 * Twelve rather than six, and the reason is the whole of `PartialRecording` below: a scenario
 * is a few dozen documents at one a second, and MusicBrainz's load-shedder goes through busy
 * spells measured in minutes. Six attempts capped at thirty seconds is about a minute and a
 * half of patience, which is less than one of those spells, so an afternoon of recording
 * became an afternoon of restarting from zero.
 */
const MAX_ATTEMPTS = 12;

/**
 * A run that ran out of patience, carrying everything it had already fetched.
 *
 * Recording is all-or-nothing per scenario, which is right — a half-scored fixture is worse
 * than none — but *throwing away the documents* is not. They cost a second each and they are
 * immutable; the next run reads them back through `existingCassette` and resumes. So the
 * partial entries travel with the failure and `main` writes them before re-raising.
 */
class PartialRecording extends Error {
  readonly entries: readonly CassetteEntry[];

  constructor(entries: readonly CassetteEntry[], cause: unknown) {
    super(`interrupted after ${String(entries.length)} document(s)`, { cause });
    this.name = "PartialRecording";
    this.entries = entries;
  }
}

/* ------------------------------------------------------------------ */
/* recording                                                           */
/* ------------------------------------------------------------------ */

interface CassetteEntry {
  readonly key: string;
  readonly payload: unknown;
}

interface SearchResult {
  readonly releases?: readonly MbRelease[];
  readonly recordings?: readonly MbRecording[];
  readonly "release-groups"?: readonly { id?: string; title?: string }[];
}

const SEARCH_LIMIT = 25;

/**
 * How many lookups are recorded, against the ceiling a match is allowed.
 *
 * The margin is not slack in the budget — the service stops when its branch and bound says
 * stop, well short of `matchLookupLimit` on every scenario here. It is insurance for the
 * replay: the ones a match opens are chosen by an attainable score, and that shifts when a
 * duration is corrected or a weight is moved, so recording four more than the ceiling means
 * such a change *moves a ranking* instead of breaking every cassette test at once with
 * "no document for …".
 */
const RECORDED_LOOKUPS = DEFAULT_LOOKUP_LIMIT + 4;

/**
 * Record an album scenario, following the **two-level** search of decision 151.
 *
 * One `release-group` search, one `release` search per group kept, and a tracklist lookup for
 * the ones the engine itself would spend them on — with the same "one reserved per group"
 * allocation `matching.service.ts` uses, so a cassette stays a recording of the real
 * algorithm's appetite rather than a guess at it.
 *
 * `known` is what a previous run already recorded. Documents already on the cassette are
 * **reused**, never re-fetched: adding a per-group search to the algorithm must add the
 * documents that search needs and change nothing else, or every assertion written against the
 * old recording is silently re-litigated by an afternoon of a different MusicBrainz.
 * `--refresh` is how you ask for the other thing.
 */
async function recordAlbum(
  scenario: AlbumScenario,
  known: ReadonlyMap<string, unknown> = new Map(),
  entries: CassetteEntry[] = [],
): Promise<{ entries: CassetteEntry[]; fixture: unknown }> {
  const written = new Set<string>();
  // Derived exactly as `match` and `mm match` derive them. Deriving them differently here is
  // what made the first recording unreplayable: a label read in one place and left null in the
  // other reordered two near-identical pressings and sent the lookups to different candidates.
  const hints = albumHints(scenario.videos);

  async function document<T>(key: string, path: string, query: Record<string, string>): Promise<T> {
    const cached = known.get(key);
    const payload = cached ?? (await get<T>(path, query));
    if (!written.has(key)) {
      written.add(key);
      entries.push({ key, payload });
    }
    return payload as T;
  }

  async function searchDocument(
    entity: "release" | "release-group" | "recording",
    query: string,
  ): Promise<SearchResult> {
    return await document<SearchResult>(
      `search/${entity}?query=${query}&limit=${String(SEARCH_LIMIT)}&offset=0`,
      entity,
      { query, limit: String(SEARCH_LIMIT), offset: "0" },
    );
  }

  /*
   * 1 — the release groups, down the same ladder `findReleaseGroups` climbs.
   *
   * First credited artist, then the whole credit, then the base title — and never the title on
   * its own, which is the rung the sixth owner review had removed. The recording-convergence
   * rung below it is recorded too, because a scenario that needs it (Laufey's *Bewitched*) has
   * to replay through it rather than around it.
   */
  const album = scenario.source.album;
  const credit = scenario.source.artist;
  const primary = primaryArtist(credit);
  const base = stripEditionQualifier(album);

  const rungs = [lucene.releaseGroupQuery(album, primary ?? credit)];
  if (primary !== null) rungs.push(lucene.releaseGroupQuery(album, credit));
  if (base !== album) rungs.push(lucene.releaseGroupQuery(base, primary ?? credit));

  let rawGroups: readonly { id?: string; title?: string }[] = [];
  for (const rung of rungs) {
    const answer = await searchDocument("release-group", rung);
    rawGroups = answer["release-groups"] ?? [];
    if (rawGroups.length > 0) break;
  }

  if (rawGroups.length === 0) {
    // The last rung: the album through its tracks. Four searches, the longest videos first,
    // exactly as `convergeThroughRecordings` picks them.
    const sample = [...scenario.videos]
      .sort((a, b) => (b.durationSeconds ?? 0) - (a.durationSeconds ?? 0) || a.index - b.index)
      .slice(0, 4);
    // The same filter `convergeThroughRecordings` applies: only recordings that carry the
    // credit vote, only groups bearing the album's name are counted, and a group needs two
    // distinct tracks to name it. A cassette that recorded a looser answer would replay a
    // ranking the service never computes.
    const converged = new Map<string, { voters: Set<number>; group: MbReleaseGroup }>();
    for (const video of sample) {
      const answer = await searchDocument(
        "recording",
        lucene.recordingQuery({
          title: stripArtistPrefix(video.ytTrack ?? video.title, primary ?? credit),
          artist: primary ?? credit,
          durationSeconds: video.durationSeconds,
        }),
      );
      const seenHere = new Set<string>();
      for (const recording of answer.recordings ?? []) {
        const credited = recording["artist-credit"] ?? [];
        const name = credited
          .map((entry) => `${entry.name ?? entry.artist?.name ?? ""}${entry.joinphrase ?? ""}`)
          .join("")
          .trim();
        if (!creditCarriesArtist(credit, name)) continue;
        for (const release of (recording as { releases?: readonly MbRelease[] }).releases ?? []) {
          const group = release["release-group"];
          const id = group?.id;
          if (group === undefined || id === undefined || seenHere.has(id)) continue;
          const title = group.title ?? release.title ?? "";
          if (titleScore(album, title) < 0.87 && titleScore(base, title) < 0.87) continue;
          seenHere.add(id);
          const entry = converged.get(id) ?? {
            voters: new Set<number>(),
            group: { ...group, "artist-credit": credited } as MbReleaseGroup,
          };
          entry.voters.add(video.index);
          converged.set(id, entry);
        }
      }
    }
    rawGroups = [...converged.values()]
      .filter((entry) => entry.voters.size >= 2)
      .sort((a, b) => b.voters.size - a.voters.size)
      .map((entry) => entry.group);
  }

  const scoredGroups = releaseGroups.searchScore(rawGroups, hints, scenario.videos.length);
  // One more group than a match keeps, for the same reason as the four extra lookups: a
  // re-scored group must be able to move without breaking every cassette test at once.
  const kept = scoredGroups.slice(0, DEFAULT_GROUP_LIMIT + 1);
  if (kept.length === 0) throw new Error(`no release group for ${scenario.name}`);

  // 2 — the releases of each kept group.
  const searchResults: MbRelease[] = [];
  const seen = new Set<string>();
  for (const group of kept) {
    const query = lucene.releaseQuery({
      album: scenario.source.album,
      releaseGroupId: group.id,
    });
    const answer = await searchDocument("release", query);
    for (const release of answer.releases ?? []) {
      if (release.id === undefined || seen.has(release.id)) continue;
      seen.add(release.id);
      searchResults.push(release);
    }
  }

  // 3 — the N the engine would look up, decided by the engine itself.
  const shallow = searchResults.map((release) => ({ release, detailed: false }));
  const prescored = releaseCandidates.score({
    videos: scenario.videos,
    hints,
    candidates: shallow,
  });
  const wanted: string[] = [];
  const takenGroups = new Set<string>();
  for (const candidate of prescored.candidates) {
    if (candidate.id === "" || takenGroups.has(candidate.releaseGroupId ?? "")) continue;
    takenGroups.add(candidate.releaseGroupId ?? "");
    wanted.push(candidate.id);
  }
  for (const candidate of prescored.candidates) {
    if (wanted.length >= RECORDED_LOOKUPS) break;
    if (candidate.id === "" || wanted.includes(candidate.id)) continue;
    wanted.push(candidate.id);
  }

  const detailed: MbRelease[] = [];
  for (const mbid of wanted.slice(0, RECORDED_LOOKUPS)) {
    const full = await document<MbRelease>(`release/${mbid}?inc=releaseFull`, `release/${mbid}`, {
      inc: INC.releaseFull,
    });
    detailed.push(full);
  }

  const detailedIds = new Set(detailed.map((release) => release.id));
  const fixture = {
    kind: "album",
    videos: scenario.videos,
    hints,
    candidates: searchResults.map((release) => {
      const full = detailed.find((candidate) => candidate.id === release.id);
      return full === undefined ? { release, detailed: false } : { release: full, detailed: true };
    }),
    groups: scoredGroups,
    lookedUp: [...detailedIds],
  };

  return { entries, fixture };
}

async function recordSingle(
  scenario: SingleScenario,
  known: ReadonlyMap<string, unknown> = new Map(),
  entries: CassetteEntry[] = [],
): Promise<{ entries: CassetteEntry[]; fixture: unknown }> {
  const written = new Set<string>();

  /**
   * Fetch a document, unless the cassette already carries it under that key.
   *
   * Two videos of the same scenario overlap heavily — the wide search is literally the same
   * request, and most of the lookups are the same recordings — and a re-record must not spend
   * a request, or risk a different answer, on a document that is already recorded.
   */
  async function document<T>(key: string, path: string, query: Record<string, string>): Promise<T> {
    const cached = known.get(key);
    const payload = cached ?? (await get<T>(path, query));
    if (!written.has(key)) {
      written.add(key);
      entries.push({ key, payload });
    }
    return payload as T;
  }

  async function forVideo(video: MatchVideo): Promise<unknown[]> {
    const title = video.ytTrack ?? video.title;

    // The same two searches the service makes: narrow to find the answer, wide to surface the
    // same-title recordings by other artists that the score has to be seen rejecting.
    const narrow = lucene.recordingQuery({
      title,
      artist: video.ytArtist ?? video.uploader ?? null,
      durationSeconds: video.durationSeconds,
    });
    const wide = lucene.recordingQuery({ title });

    const merged: MbRecording[] = [];
    const seen = new Set<string>();
    for (const query of [narrow, wide]) {
      const found = await document<SearchResult>(
        `search/recording?query=${query}&limit=${String(SEARCH_LIMIT)}&offset=0`,
        "recording",
        { query, limit: String(SEARCH_LIMIT), offset: "0" },
      );
      for (const recording of found.recordings ?? []) {
        if (recording.id === undefined || seen.has(recording.id)) continue;
        seen.add(recording.id);
        merged.push(recording);
      }
    }

    const candidates: unknown[] = [];
    for (const [index, recording] of merged.entries()) {
      if (recording.id === undefined) continue;
      let releases = (recording as { releases?: readonly MbRelease[] }).releases ?? [];
      if (index < RECORDED_LOOKUPS) {
        const full = await document<MbRecording & { releases?: readonly MbRelease[] }>(
          `recording/${recording.id}?inc=recordingBorrow`,
          `recording/${recording.id}`,
          { inc: INC.recordingBorrow },
        );
        if (full.releases !== undefined) releases = full.releases;
      }
      const credited = recording["artist-credit"] ?? [];
      candidates.push({
        id: recording.id,
        title: recording.title ?? "",
        artist: credited
          .map((entry) => `${entry.name ?? entry.artist?.name ?? ""}${entry.joinphrase ?? ""}`)
          .join("")
          .trim(),
        disambiguation: recording.disambiguation ?? "",
        lengthMs: recording.length ?? null,
        isrcs: recording.isrcs ?? [],
        searchScore: (recording as { score?: number }).score ?? null,
        releases,
      });
    }
    return candidates;
  }

  // The pure-engine fixture is the first video's scenario, and only that one.
  const candidates = await forVideo(scenario.video);
  for (const other of scenario.alsoVideos ?? []) await forVideo(other);

  return { entries, fixture: { kind: "single", video: scenario.video, candidates } };
}

/* ------------------------------------------------------------------ */
/* main                                                                */
/* ------------------------------------------------------------------ */

const CASSETTE_DIR = join(repoRoot, "apps", "web", "test", "cassettes", "matching");
const FIXTURE_DIR = join(repoRoot, "packages", "domain", "fixtures", "matching");

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

/** The documents a previous run of this scenario already recorded, by cache key. */
function existingCassette(name: string): Map<string, unknown> {
  const path = join(CASSETTE_DIR, `${name}.json`);
  if (!existsSync(path)) return new Map();
  const parsed = JSON.parse(readFileSync(path, "utf8")) as {
    entries?: readonly { key: string; payload: unknown }[];
  };
  return new Map((parsed.entries ?? []).map((entry) => [entry.key, entry.payload]));
}

async function main(): Promise<void> {
  const wanted = process.argv.slice(2).filter((arg) => !arg.startsWith("--"));
  const dry = process.argv.includes("--dry");
  const chosen = wanted.length === 0 ? SCENARIOS : SCENARIOS.filter((s) => wanted.includes(s.name));
  if (chosen.length === 0) {
    console.error(`unknown scenario. Known: ${SCENARIOS.map((s) => s.name).join(", ")}`);
    process.exit(1);
  }

  mkdirSync(CASSETTE_DIR, { recursive: true });
  mkdirSync(FIXTURE_DIR, { recursive: true });
  const recordedAt = new Date().toISOString();

  for (const scenario of chosen) {
    console.log(`recording ${scenario.name}…`);
    /*
     * Documents already in the cassette are kept rather than re-fetched.
     *
     * A cassette is a recording of one afternoon's MusicBrainz. Adding a video to a scenario
     * must add the documents that video needs and change nothing else — otherwise every
     * assertion written against the old recording is re-litigated by a run that was only ever
     * meant to be additive. `--refresh` is the way to ask for the other thing.
     */
    const previous = existingCassette(scenario.name);
    const known = process.argv.includes("--refresh") ? new Map<string, unknown>() : previous;
    const gathered: CassetteEntry[] = [];
    let entries: CassetteEntry[];
    let fixture: unknown;
    try {
      ({ entries, fixture } =
        scenario.kind === "album"
          ? await recordAlbum(scenario, known, gathered)
          : await recordSingle(scenario, known, gathered));
    } catch (error) {
      /*
       * Keep what was fetched, then re-raise.
       *
       * Every document here cost a second and none of them will ever change under this key, so
       * a run that MusicBrainz's load-shedder interrupts must not make the next one start from
       * zero — `existingCassette` reads exactly this file back as `known`. The *fixture* is
       * deliberately not written: it is derived from the whole set, and half of one would be a
       * ranking nobody recorded.
       */
      if (!dry && gathered.length > 0) {
        writeJson(join(CASSETTE_DIR, `${scenario.name}.json`), {
          name: scenario.name,
          kind: scenario.kind,
          recordedAt,
          source: scenario.source,
          videos: scenario.kind === "album" ? scenario.videos : [scenario.video],
          entries: gathered,
          partial: true,
        });
        console.log(
          `  interrupted — ${String(gathered.length)} document(s) kept; run it again to resume`,
        );
      }
      throw new PartialRecording(gathered, error);
    }

    const cassette = {
      name: scenario.name,
      kind: scenario.kind,
      recordedAt,
      source: scenario.source,
      videos: scenario.kind === "album" ? scenario.videos : [scenario.video],
      entries,
    };

    if (dry) {
      console.log(`  ${String(entries.length)} document(s), not written (--dry)`);
      continue;
    }
    writeJson(join(CASSETTE_DIR, `${scenario.name}.json`), cassette);
    writeJson(join(FIXTURE_DIR, `${scenario.name}.json`), fixture);
    console.log(`  ${String(entries.length)} document(s) written`);
  }

  console.log(`\n${String(requests)} MusicBrainz request(s), at most one per second.`);
}

await main();
