/**
 * Record the five matching scenarios from the real MusicBrainz.
 *
 * `bun run scripts/record-matching-cassettes.ts [name…] [--dry]`
 *
 * Run **once**, by hand, with `MM_MB_CONTACT` set. It writes two things per scenario:
 *
 *  - `apps/web/test/cassettes/matching/<name>.json` — every MusicBrainz document one match
 *    touches, under the exact cache key `integrations/musicbrainz.ts` computes for it. Seeding
 *    those rows and running the service `offline` replays the match without a socket.
 *  - `packages/domain/fixtures/matching/<name>.json` — the same documents reduced to the pure
 *    engine's input, so `packages/domain` can test the scoring without importing anything from
 *    `apps/web`.
 *
 * It obeys the one-request-per-second rule itself rather than borrowing the app's limiter,
 * because it must run without a database and the limiter lives behind the cache. The contact
 * is read from the environment and never printed: the User-Agent is the one thing MusicBrainz
 * asks for and the one thing that must not end up in a committed file.
 *
 * The requests it makes are exactly the ones the service makes, in the same order, decided by
 * the same pure engine — one release-group search, one release search per group kept, and the
 * top-N lookups chosen by pre-scoring the results here too (decision 151). A cassette is
 * therefore a recording of the real algorithm's appetite, not a guess at it.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  albumHints,
  DEFAULT_GROUP_LIMIT,
  DEFAULT_LOOKUP_LIMIT,
  lucene,
  releaseCandidates,
  releaseGroups,
  type MatchVideo,
} from "../packages/domain/src/matching/index.ts";
import type {
  MbRecording,
  MbRelease,
} from "../packages/domain/src/metadata/resolvers/musicbrainz-types.ts";
import { prune } from "./prune-musicbrainz.ts";
import { repoRoot } from "./lib.ts";

/* ------------------------------------------------------------------ */
/* the scenarios                                                       */
/* ------------------------------------------------------------------ */

interface AlbumScenario {
  readonly name: string;
  readonly kind: "album";
  readonly source: {
    url: string;
    album: string;
    artist: string;
    year: number;
    label: string;
    note?: string;
  };
  readonly videos: readonly MatchVideo[];
}

interface SingleScenario {
  readonly name: string;
  readonly kind: "single";
  readonly source: { url: string; note?: string };
  readonly video: MatchVideo;
  /**
   * Other videos the same cassette must be able to answer.
   *
   * `videos[0]` is the scenario the phase table describes and the only one the pure-engine
   * fixture is built from — deliberately *not* what the toolbox fixture serves, which is the
   * whole point of a cassette that needs neither Docker nor a network. But the Console's
   * wizard resolves through the toolbox, so on `fixture://skinny-love` it matches the *other*
   * video, with a different artist clause and a different duration window, and the cassette
   * had no document for it: step 2 of a single could not be exercised offline at all
   * (DRIVE-1 §A1, when a spec was finally written for it). Recording both keeps the scenario
   * and makes the fixture pair usable end to end.
   */
  readonly alsoVideos?: readonly MatchVideo[];
}

type Scenario = AlbumScenario | SingleScenario;

interface AlbumCommon {
  readonly album: string;
  readonly artist: string;
  readonly year: number;
  readonly uploader: string;
  readonly label: string;
  readonly releasedOn: string;
}

/**
 * The "Auto-generated by YouTube" blurb, in the exact shape `normalize/youtube-description.ts`
 * parses. It is the only place the label and the exact release date ever appear, which is why
 * the matcher reads it at all.
 */
function autoDescription(of: AlbumCommon & { track: string }): string {
  return [
    `Provided to YouTube by ${of.label}`,
    "",
    `${of.track} · ${of.artist}`,
    "",
    of.album,
    "",
    `℗ ${String(of.year)} ${of.label}`,
    "",
    `Released on: ${of.releasedOn}`,
    "",
    "Auto-generated by YouTube.",
  ].join("\n");
}

/** Build an album's video list from `[title, seconds]` pairs, all sharing the YouTube tags. */
function albumVideos(
  entries: readonly (readonly [string, number, string?])[],
  common: AlbumCommon,
): MatchVideo[] {
  return entries.map(([title, duration, trackTag], index) => ({
    id: `yt-${common.album.toLowerCase().replace(/\W+/g, "-")}-${String(index + 1)}`,
    index,
    title,
    durationSeconds: duration,
    uploader: common.uploader,
    ytTrack: trackTag ?? title,
    ytArtist: common.artist,
    ytAlbum: common.album,
    ytReleaseYear: common.year,
    description: autoDescription({ ...common, track: trackTag ?? title }),
  }));
}

const DISCOVERY: AlbumScenario = {
  name: "discovery",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_discovery",
    album: "Discovery",
    artist: "Daft Punk",
    year: 2001,
    // "Provided to YouTube by Parlophone France" — the distributor today, not the 2001 imprint.
    label: "Parlophone France",
    note: "15 videos for a 14-track album: the last one is a radio edit and must end up extra.",
  },
  videos: albumVideos(
    [
      ["One More Time", 320],
      ["Aerodynamic", 207],
      ["Digital Love", 298],
      ["Harder Better Faster Stronger", 224, "Harder, Better, Faster, Stronger"],
      ["Crescendolls", 211],
      ["Nightvision", 104],
      ["Superheroes", 238],
      ["High Life", 202],
      ["Something About Us", 231],
      ["Voyager", 227],
      ["Veridis Quo", 344],
      ["Short Circuit", 206],
      ["Face to Face", 238],
      ["Too Long", 600],
      ["One More Time (Radio Edit)", 233, "One More Time"],
    ],
    {
      album: "Discovery",
      artist: "Daft Punk",
      year: 2001,
      uploader: "Daft Punk - Topic",
      label: "Parlophone (France)",
      releasedOn: "2001-03-12",
    },
  ),
};

const CURRENTS: AlbumScenario = {
  name: "currents",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_currents",
    album: "Currents",
    artist: "Tame Impala",
    year: 2015,
    label: "Modular Recordings",
    note: "11 videos for a 13-track album: “Gossip” and “Disciples” are missing and must be reported uncovered.",
  },
  // Durations within a second of the release's own, which is what a YouTube Music rip looks
  // like, and titles in YouTube's title case with straight apostrophes — so the normaliser is
  // exercised rather than bypassed. Tracks 6 (Gossip) and 9 (Disciples) have no video.
  videos: albumVideos(
    [
      ["Let It Happen", 467],
      ["Nangs", 108],
      ["The Moment", 254],
      ["Yes I'm Changing", 270],
      ["Eventually", 320],
      ["The Less I Know The Better", 218],
      ["Past Life", 226],
      ["'Cause I'm A Man", 241],
      ["Reality In Motion", 252],
      ["Love/Paranoia", 187],
      ["New Person, Same Old Mistakes", 363],
    ],
    {
      album: "Currents",
      artist: "Tame Impala",
      year: 2015,
      uploader: "Tame Impala - Topic",
      label: "Modular Recordings",
      releasedOn: "2015-07-17",
    },
  ),
};

const SKINNY_LOVE: SingleScenario = {
  name: "skinny-love",
  kind: "single",
  source: {
    url: "https://www.youtube.com/watch?v=skinny-love",
    note: "Birdy's cover, not Bon Iver's original: same title, same song, thirty-six seconds apart.",
  },
  video: {
    id: "yt-skinny-love",
    index: 0,
    title: "Birdy - Skinny Love [Official Music Video]",
    durationSeconds: 202,
    uploader: "Birdy",
    ytTrack: "Skinny Love",
    ytArtist: "Birdy",
    ytAlbum: "Birdy",
    ytReleaseYear: 2011,
  },
  // Verbatim from `services/toolbox/src/toolbox/fixtures/data/skinny-love.json`, so that
  // `fixture://skinny-love` replays in the Console exactly as it does in `mm match`.
  alsoVideos: [
    {
      id: "MVzhTGx2Lec",
      index: 0,
      title: "Skinny Love",
      durationSeconds: 238,
      uploader: "Bon Iver - Topic",
      ytTrack: "Skinny Love",
      ytArtist: "Bon Iver",
      ytAlbum: "For Emma, Forever Ago",
      ytReleaseYear: 2007,
    },
  ],
};

const FORMIDABLE: SingleScenario = {
  name: "formidable",
  kind: "single",
  source: {
    url: "https://www.youtube.com/watch?v=formidable",
    note: "Album version 3:34 against the single edit 3:33 — one second apart, which is inside the tolerance.",
  },
  video: {
    id: "yt-formidable",
    index: 0,
    title: "Stromae - Formidable (clip officiel)",
    durationSeconds: 214,
    uploader: "Stromae",
    ytTrack: "Formidable",
    ytArtist: "Stromae",
    ytReleaseYear: 2013,
  },
};

/**
 * The third owner review's counter-example, recorded from the real thing.
 *
 * Eleven videos of Tessa Violet's *Bad Ideas*, exactly as `yt-dlp` reports the YouTube Music
 * album playlist `OLAK5uy_lMECD_…`. MusicBrainz files that name four ways — the 2019 album,
 * a 2022 deluxe vinyl in the same group, a 2019 EP called "Bad Ideas (Act One)", and a 2020
 * one-track single — which is what made the single-group search of the previous algorithm
 * offer one candidate at 94 %. It is here so that never becomes true again silently.
 */
const BAD_IDEAS: AlbumScenario = {
  name: "bad-ideas",
  kind: "album",
  source: {
    url: "https://music.youtube.com/playlist?list=OLAK5uy_lMECD_tHQnZ8tr8_mQZr2I8usqrw9eCrs",
    album: "Bad Ideas",
    artist: "Tessa Violet",
    year: 2019,
    label: "T∆G Music",
    note: "11 videos, and four release groups share the name: album, deluxe, EP, and a one-track single. The single must not win (owner review 3, D3).",
  },
  videos: albumVideos(
    [
      ["Prelude", 64],
      ["Crush", 216],
      ["Bad Ideas", 179],
      ["I Like (the idea of) You", 170],
      ["Games", 221],
      ["Feelin", 184],
      ["Words Ain't Enough", 124],
      ["Bored", 183],
      ["Wishful Drinking", 195],
      ["Honest", 252],
      ["Interlude III", 170],
    ],
    {
      album: "Bad Ideas",
      artist: "Tessa Violet",
      year: 2019,
      uploader: "Tessa Violet",
      label: "T∆G Music",
      releasedOn: "2019-10-25",
    },
  ),
};

const SCENARIOS: readonly Scenario[] = [DISCOVERY, SKINNY_LOVE, CURRENTS, FORMIDABLE, BAD_IDEAS];

/* ------------------------------------------------------------------ */
/* the wire                                                            */
/* ------------------------------------------------------------------ */

const BASE = "https://musicbrainz.org/ws/2";
const MIN_INTERVAL_MS = 1_100; // a little over one second, so a clock skew cannot make it two

/** `inc=` lists — kept in step with `apps/web/src/server/integrations/musicbrainz.ts`. */
const INC = {
  releaseFull:
    "artists+artist-credits+labels+recordings+release-groups+media+isrcs+genres+tags+aliases+artist-rels+recording-rels+work-rels+recording-level-rels+work-level-rels+url-rels",
  // The matcher looks a recording up to learn which releases it is on, so it asks for the
  // app.s `recordingBorrow` preset — the same list, under the same cache key.
  recordingBorrow:
    "artists+artist-credits+isrcs+genres+tags+aliases+artist-rels+work-rels+url-rels+work-level-rels+releases+release-groups+media",
} as const;

let lastCall = 0;
let requests = 0;

function readContact(): string {
  const fromEnv = process.env["MM_MB_CONTACT"];
  if (fromEnv !== undefined && fromEnv.trim() !== "") return fromEnv.trim();
  const envFile = join(repoRoot, ".env");
  if (existsSync(envFile)) {
    for (const line of readFileSync(envFile, "utf8").split(/\r?\n/)) {
      const match = /^\s*MM_MB_CONTACT\s*=\s*(.*)$/.exec(line);
      if (match?.[1] !== undefined) return match[1].trim().replace(/^["']|["']$/g, "");
    }
  }
  throw new Error(
    "MM_MB_CONTACT is not set. Put it in v2/.env (gitignored) before recording cassettes.",
  );
}

const USER_AGENT = `MusicManager/0.0.0 ( ${readContact()} )`;

async function pace(): Promise<void> {
  const wait = lastCall + MIN_INTERVAL_MS - Date.now();
  if (wait > 0) await new Promise((r) => setTimeout(r, wait));
  lastCall = Date.now();
}

/**
 * One request, paced and retried.
 *
 * `503` from MusicBrainz means "busy", not "wrong": the `inc=` list of a full release lookup
 * is expensive and their load-shedder says so several times an hour. Backing off and asking
 * again is the documented answer, and a recorder that gave up on the first one would have to
 * be babysat through a four-scenario run.
 */
async function get<T>(path: string, query: Record<string, string>): Promise<T> {
  const search = new URLSearchParams({ ...query, fmt: "json" });
  const url = `${BASE}/${path}?${search.toString()}`;
  let backoff = 2_000;

  for (let attempt = 1; ; attempt += 1) {
    await pace();
    const response = await fetch(url, { headers: { "user-agent": USER_AGENT } });
    requests += 1;
    if (response.ok) return prune(await response.json()) as T;

    const body = await response.text();
    const retryable = response.status === 503 || response.status === 429 || response.status >= 500;
    if (!retryable || attempt >= 6) {
      throw new Error(`MusicBrainz answered ${String(response.status)} for ${path} — ${body}`);
    }
    console.log(`  ${String(response.status)} on ${path}, retrying in ${String(backoff / 1000)}s…`);
    await new Promise((r) => setTimeout(r, backoff));
    backoff = Math.min(backoff * 2, 30_000);
  }
}

/* ------------------------------------------------------------------ */
/* recording                                                           */
/* ------------------------------------------------------------------ */

interface CassetteEntry {
  readonly key: string;
  readonly payload: unknown;
}

interface SearchResult {
  readonly releases?: readonly MbRelease[];
  readonly recordings?: readonly MbRecording[];
  readonly "release-groups"?: readonly { id?: string; title?: string }[];
}

const SEARCH_LIMIT = 25;

/**
 * How many lookups are recorded, against the six a match spends.
 *
 * The margin is not slack in the budget — the service still stops at `matchLookupLimit`. It is
 * insurance for the replay: the six a match picks are decided by a pre-score, and a pre-score
 * shifts when a duration is corrected or a preference is changed. Recording ten means such a
 * change moves the ranking instead of breaking every cassette test at once.
 */
const RECORDED_LOOKUPS = DEFAULT_LOOKUP_LIMIT + 4;

/**
 * Record an album scenario, following the **two-level** search of decision 151.
 *
 * One `release-group` search, one `release` search per group kept, and a tracklist lookup for
 * the ones the engine itself would spend them on — with the same "one reserved per group"
 * allocation `matching.service.ts` uses, so a cassette stays a recording of the real
 * algorithm's appetite rather than a guess at it.
 *
 * `known` is what a previous run already recorded. Documents already on the cassette are
 * **reused**, never re-fetched: adding a per-group search to the algorithm must add the
 * documents that search needs and change nothing else, or every assertion written against the
 * old recording is silently re-litigated by an afternoon of a different MusicBrainz.
 * `--refresh` is how you ask for the other thing.
 */
async function recordAlbum(
  scenario: AlbumScenario,
  known: ReadonlyMap<string, unknown> = new Map(),
): Promise<{ entries: CassetteEntry[]; fixture: unknown }> {
  const entries: CassetteEntry[] = [];
  const written = new Set<string>();
  // Derived exactly as `match` and `mm match` derive them. Deriving them differently here is
  // what made the first recording unreplayable: a label read in one place and left null in the
  // other reordered two near-identical pressings and sent the lookups to different candidates.
  const hints = albumHints(scenario.videos);

  async function document<T>(key: string, path: string, query: Record<string, string>): Promise<T> {
    const cached = known.get(key);
    const payload = cached ?? (await get<T>(path, query));
    if (!written.has(key)) {
      written.add(key);
      entries.push({ key, payload });
    }
    return payload as T;
  }

  async function searchDocument(
    entity: "release" | "release-group",
    query: string,
  ): Promise<SearchResult> {
    return await document<SearchResult>(
      `search/${entity}?query=${query}&limit=${String(SEARCH_LIMIT)}&offset=0`,
      entity,
      { query, limit: String(SEARCH_LIMIT), offset: "0" },
    );
  }

  // 1 — the release groups, narrow then (only if empty) wide, as the service asks them.
  const narrow = lucene.releaseGroupQuery(scenario.source.album, scenario.source.artist);
  let found = await searchDocument("release-group", narrow);
  let rawGroups = found["release-groups"] ?? [];
  if (rawGroups.length === 0) {
    found = await searchDocument(
      "release-group",
      lucene.releaseGroupQueryWide(scenario.source.album),
    );
    rawGroups = found["release-groups"] ?? [];
  }

  const scoredGroups = releaseGroups.searchScore(rawGroups, hints, scenario.videos.length);
  // One more group than a match keeps, for the same reason as the four extra lookups: a
  // re-scored group must be able to move without breaking every cassette test at once.
  const kept = scoredGroups.slice(0, DEFAULT_GROUP_LIMIT + 1);
  if (kept.length === 0) throw new Error(`no release group for ${scenario.name}`);

  // 2 — the releases of each kept group.
  const searchResults: MbRelease[] = [];
  const seen = new Set<string>();
  for (const group of kept) {
    const query = lucene.releaseQuery({
      album: scenario.source.album,
      releaseGroupId: group.id,
    });
    const answer = await searchDocument("release", query);
    for (const release of answer.releases ?? []) {
      if (release.id === undefined || seen.has(release.id)) continue;
      seen.add(release.id);
      searchResults.push(release);
    }
  }

  // 3 — the N the engine would look up, decided by the engine itself.
  const shallow = searchResults.map((release) => ({ release, detailed: false }));
  const prescored = releaseCandidates.score({
    videos: scenario.videos,
    hints,
    candidates: shallow,
  });
  const wanted: string[] = [];
  const takenGroups = new Set<string>();
  for (const candidate of prescored.candidates) {
    if (candidate.id === "" || takenGroups.has(candidate.releaseGroupId ?? "")) continue;
    takenGroups.add(candidate.releaseGroupId ?? "");
    wanted.push(candidate.id);
  }
  for (const candidate of prescored.candidates) {
    if (wanted.length >= RECORDED_LOOKUPS) break;
    if (candidate.id === "" || wanted.includes(candidate.id)) continue;
    wanted.push(candidate.id);
  }

  const detailed: MbRelease[] = [];
  for (const mbid of wanted.slice(0, RECORDED_LOOKUPS)) {
    const full = await document<MbRelease>(`release/${mbid}?inc=releaseFull`, `release/${mbid}`, {
      inc: INC.releaseFull,
    });
    detailed.push(full);
  }

  const detailedIds = new Set(detailed.map((release) => release.id));
  const fixture = {
    kind: "album",
    videos: scenario.videos,
    hints,
    candidates: searchResults.map((release) => {
      const full = detailed.find((candidate) => candidate.id === release.id);
      return full === undefined ? { release, detailed: false } : { release: full, detailed: true };
    }),
    groups: scoredGroups,
    lookedUp: [...detailedIds],
  };

  return { entries, fixture };
}

async function recordSingle(
  scenario: SingleScenario,
  known: ReadonlyMap<string, unknown> = new Map(),
): Promise<{ entries: CassetteEntry[]; fixture: unknown }> {
  const entries: CassetteEntry[] = [];
  const written = new Set<string>();

  /**
   * Fetch a document, unless the cassette already carries it under that key.
   *
   * Two videos of the same scenario overlap heavily — the wide search is literally the same
   * request, and most of the lookups are the same recordings — and a re-record must not spend
   * a request, or risk a different answer, on a document that is already recorded.
   */
  async function document<T>(key: string, path: string, query: Record<string, string>): Promise<T> {
    const cached = known.get(key);
    const payload = cached ?? (await get<T>(path, query));
    if (!written.has(key)) {
      written.add(key);
      entries.push({ key, payload });
    }
    return payload as T;
  }

  async function forVideo(video: MatchVideo): Promise<unknown[]> {
    const title = video.ytTrack ?? video.title;

    // The same two searches the service makes: narrow to find the answer, wide to surface the
    // same-title recordings by other artists that the score has to be seen rejecting.
    const narrow = lucene.recordingQuery({
      title,
      artist: video.ytArtist ?? video.uploader ?? null,
      durationSeconds: video.durationSeconds,
    });
    const wide = lucene.recordingQuery({ title });

    const merged: MbRecording[] = [];
    const seen = new Set<string>();
    for (const query of [narrow, wide]) {
      const found = await document<SearchResult>(
        `search/recording?query=${query}&limit=${String(SEARCH_LIMIT)}&offset=0`,
        "recording",
        { query, limit: String(SEARCH_LIMIT), offset: "0" },
      );
      for (const recording of found.recordings ?? []) {
        if (recording.id === undefined || seen.has(recording.id)) continue;
        seen.add(recording.id);
        merged.push(recording);
      }
    }

    const candidates: unknown[] = [];
    for (const [index, recording] of merged.entries()) {
      if (recording.id === undefined) continue;
      let releases = (recording as { releases?: readonly MbRelease[] }).releases ?? [];
      if (index < RECORDED_LOOKUPS) {
        const full = await document<MbRecording & { releases?: readonly MbRelease[] }>(
          `recording/${recording.id}?inc=recordingBorrow`,
          `recording/${recording.id}`,
          { inc: INC.recordingBorrow },
        );
        if (full.releases !== undefined) releases = full.releases;
      }
      const credited = recording["artist-credit"] ?? [];
      candidates.push({
        id: recording.id,
        title: recording.title ?? "",
        artist: credited
          .map((entry) => `${entry.name ?? entry.artist?.name ?? ""}${entry.joinphrase ?? ""}`)
          .join("")
          .trim(),
        disambiguation: recording.disambiguation ?? "",
        lengthMs: recording.length ?? null,
        isrcs: recording.isrcs ?? [],
        searchScore: (recording as { score?: number }).score ?? null,
        releases,
      });
    }
    return candidates;
  }

  // The pure-engine fixture is the first video's scenario, and only that one.
  const candidates = await forVideo(scenario.video);
  for (const other of scenario.alsoVideos ?? []) await forVideo(other);

  return { entries, fixture: { kind: "single", video: scenario.video, candidates } };
}

/* ------------------------------------------------------------------ */
/* main                                                                */
/* ------------------------------------------------------------------ */

const CASSETTE_DIR = join(repoRoot, "apps", "web", "test", "cassettes", "matching");
const FIXTURE_DIR = join(repoRoot, "packages", "domain", "fixtures", "matching");

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

/** The documents a previous run of this scenario already recorded, by cache key. */
function existingCassette(name: string): Map<string, unknown> {
  const path = join(CASSETTE_DIR, `${name}.json`);
  if (!existsSync(path)) return new Map();
  const parsed = JSON.parse(readFileSync(path, "utf8")) as {
    entries?: readonly { key: string; payload: unknown }[];
  };
  return new Map((parsed.entries ?? []).map((entry) => [entry.key, entry.payload]));
}

async function main(): Promise<void> {
  const wanted = process.argv.slice(2).filter((arg) => !arg.startsWith("--"));
  const dry = process.argv.includes("--dry");
  const chosen = wanted.length === 0 ? SCENARIOS : SCENARIOS.filter((s) => wanted.includes(s.name));
  if (chosen.length === 0) {
    console.error(`unknown scenario. Known: ${SCENARIOS.map((s) => s.name).join(", ")}`);
    process.exit(1);
  }

  mkdirSync(CASSETTE_DIR, { recursive: true });
  mkdirSync(FIXTURE_DIR, { recursive: true });
  const recordedAt = new Date().toISOString();

  for (const scenario of chosen) {
    console.log(`recording ${scenario.name}…`);
    /*
     * Documents already in the cassette are kept rather than re-fetched.
     *
     * A cassette is a recording of one afternoon's MusicBrainz. Adding a video to a scenario
     * must add the documents that video needs and change nothing else — otherwise every
     * assertion written against the old recording is re-litigated by a run that was only ever
     * meant to be additive. `--refresh` is the way to ask for the other thing.
     */
    const previous = existingCassette(scenario.name);
    const known = process.argv.includes("--refresh") ? new Map<string, unknown>() : previous;
    const { entries, fixture } =
      scenario.kind === "album"
        ? await recordAlbum(scenario, known)
        : await recordSingle(scenario, known);

    const cassette = {
      name: scenario.name,
      kind: scenario.kind,
      recordedAt,
      source: scenario.source,
      videos: scenario.kind === "album" ? scenario.videos : [scenario.video],
      entries,
    };

    if (dry) {
      console.log(`  ${String(entries.length)} document(s), not written (--dry)`);
      continue;
    }
    writeJson(join(CASSETTE_DIR, `${scenario.name}.json`), cassette);
    writeJson(join(FIXTURE_DIR, `${scenario.name}.json`), fixture);
    console.log(`  ${String(entries.length)} document(s) written`);
  }

  console.log(`\n${String(requests)} MusicBrainz request(s), at most one per second.`);
}

await main();
