/**
 * `bun run toolbox:openapi` — regenerate the typed contract for the Python toolbox.
 *
 * The FastAPI app is imported (not served) and asked for its OpenAPI document, which is
 * written with sorted keys so that two consecutive runs produce byte-identical files.
 * `openapi-typescript` then turns it into the client types used by `apps/web` on the
 * server side only — the browser never talks to Python.
 *
 * Never edit packages/contracts/toolbox/ by hand.
 */
import { mkdir } from "node:fs/promises";
import { join, relative } from "node:path";
import { bunx, capture, repoRoot, runSequence, toolboxDir, resolveUv } from "./lib.ts";

const outDir = join(repoRoot, "packages", "contracts", "toolbox");
const openapiPath = join(outDir, "openapi.json");
const clientPath = join(outDir, "client.d.ts");
const contractPath = join(outDir, "contract.ts");

/*
 * The hash is computed **by Python**, never here.
 *
 * The running image computes it too, from its own `app.openapi()`, and the app compares the
 * two to detect a container older than the code calling it. Two implementations of the same
 * canonicalisation would eventually disagree about something that is not a real difference —
 * Python escapes non-ASCII on the way out and JavaScript does not, to name the first one — and
 * a staleness warning that fires on a reformatting is a warning nobody reads. So there is one
 * implementation, in `toolbox/contract.py`, and this script asks it.
 */
const DUMP = [
  "import json",
  "from toolbox.app import app",
  "from toolbox.contract import SCHEMA_VERSION, contract_hash",
  "doc = app.openapi()",
  "print(json.dumps({'openapi': doc, 'schemaVersion': SCHEMA_VERSION, " +
    "'contractHash': contract_hash(doc)}, indent=2, sort_keys=True))",
].join("; ");

await mkdir(outDir, { recursive: true });

console.log("=== dumping the toolbox OpenAPI document ===");
const dumped = await capture({
  label: "openapi dump",
  cmd: [resolveUv(), "run", "python", "-c", DUMP],
  cwd: toolboxDir,
});
if (dumped.code !== 0) {
  console.error(dumped.stderr);
  process.exit(dumped.code);
}

const envelope = JSON.parse(dumped.stdout) as {
  openapi: unknown;
  schemaVersion: number;
  contractHash: string;
};
await Bun.write(openapiPath, `${JSON.stringify(envelope.openapi, null, 2)}\n`);
console.log(`wrote ${relative(repoRoot, openapiPath)}`);

await Bun.write(
  contractPath,
  [
    "/**",
    " * Which toolbox contract this checkout was generated against.",
    " *",
    " * Generated by `bun run toolbox:openapi` — **never edit by hand**, like everything else",
    " * under `packages/contracts/toolbox/`.",
    " *",
    " * `GET /health` on the toolbox reports the same two values, computed from the document the",
    " * running image actually serves. When they differ, the container is not the one this code",
    " * was built for: every call that sends a field its models do not know about comes back as a",
    " * 422 `extra_forbidden`, which reads like a bug in the app and is not one. `get_status`",
    " * compares them and says so before anything fails.",
    " */",
    `export const TOOLBOX_SCHEMA_VERSION = ${String(envelope.schemaVersion)};`,
    "",
    `export const TOOLBOX_CONTRACT_HASH = ${JSON.stringify(envelope.contractHash)};`,
    "",
  ].join("\n"),
);
console.log(`wrote ${relative(repoRoot, contractPath)}  (${envelope.contractHash})`);

await runSequence([
  {
    label: "openapi-typescript",
    cmd: bunx("openapi-typescript", openapiPath, "-o", clientPath),
  },
]);
console.log(`wrote ${relative(repoRoot, clientPath)}`);
